# Generated by Django 3.2 on 2021-09-06 15:20

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired')], default='A', max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('english_address', models.CharField(blank=True, max_length=300, null=True)),
                ('chinese_address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('province_region', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('gif', models.CharField(blank=True, max_length=300, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('handover_method', models.CharField(choices=[('O', 'Offline_pickup'), ('S', 'Shipping'), ('A', 'any')], default='A', max_length=1)),
                ('bidding', models.BooleanField(default=False)),
                ('max_bid_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('bids_count', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Classified',
                'verbose_name_plural': 'Classifieds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ClassifiedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('image_mid_size', models.CharField(max_length=300)),
                ('image_thumb', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedOrder',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_offline', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('recipient_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('tracking_number', models.CharField(blank=True, max_length=600, null=True)),
                ('buyer_transaction_id', models.CharField(blank=True, max_length=600, null=True)),
                ('seller_transaction_id', models.CharField(blank=True, max_length=600, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('recipient_chinese_address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('A', 'Awaiting'), ('C', 'Confirmed'), ('D', 'Dispatched'), ('F', 'Fetched'), ('I', 'Inferred'), ('R', 'Reimbursed'), ('X', 'Axed')], default='A', max_length=1)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Classifieds_Order',
                'verbose_name_plural': 'Classifieds_orders',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ClassifiedTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Classifieds Tag',
                'verbose_name_plural': 'Classifieds Tags',
            },
        ),
        migrations.CreateModel(
            name='OfficialAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=2000)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_region', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'OfficialAd',
                'verbose_name_plural': 'OfficialAds',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='OfficialAdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedClassifieds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'verbose_name': 'Classified tag',
                'verbose_name_plural': 'Classified Tags',
            },
        ),
        migrations.CreateModel(
            name='WxClassified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True)),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'WxClassified',
                'verbose_name_plural': 'WxClassifieds',
                'ordering': ('-timestamp',),
            },
        ),
    ]
