# Generated by Django 3.2 on 2021-09-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('classifieds', '0001_initial'),
        ('users', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxclassified',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='users.wechatuser'),
        ),
        migrations.AddField(
            model_name='taggedclassifieds',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifieds_taggedclassifieds_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='taggedclassifieds',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifieds_taggedclassifieds_items', to='classifieds.classifiedtags'),
        ),
        migrations.AddField(
            model_name='officialadimages',
            name='official_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.officialad'),
        ),
        migrations.AddField(
            model_name='officialad',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='officialad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifiedorder',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifiedorder',
            name='classified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_order', to='classifieds.classified'),
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='classified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.classified'),
        ),
        migrations.AddField(
            model_name='classifiedimages',
            name='wx_classified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds.wxclassified'),
        ),
        migrations.AddField(
            model_name='classified',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='classifieds.TaggedClassifieds', to='classifieds.ClassifiedTags', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='classified',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
